paths:
  /review/add:
    post:
      summary: "Create Review"
      description: "Create a new review."
      parameters:
        - in: body
          name: review
          description: "Review object to be created"
          required: true
          schema:
            type: object
            properties:
              member_id:
                type: integer
                description: "Member ID associated with the review."
              store_id:
                type: integer
                description: "Store ID associated with the review."
              rating:
                type: number
                description: "Review rating."
              comment:
                type: string
                description: "Review comment or description."
      responses:
        201:
          description: "Successful response indicating the review was created."
          schema:
            type: "object"
            properties:
              id:
                type: "integer"
                description: "Review ID."
              member_id:
                type: "integer"
                description: "Member ID associated with the review."
              store_id:
                type: "integer"
                description: "Store ID associated with the review."
              rating:
                type: "number"
                description: "Review rating."
              comment:
                type: "string"
                description: "Review comment or description."
              created_at:
                type: "string"
                format: "date-time"
                description: "Timestamp indicating the review creation time."
              updated_at:
                type: "string"
                format: "date-time"
                description: "Timestamp indicating the last update time of the review."
        400:
          description: "Bad Request if the request body is missing or invalid."
        500:
          description: "Internal Server Error if there is an issue with the server."